name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      env:
        credentials_json: ${{ secrets.GCP_KEY }}
        project_id: neural-water-404520
        region: us-central1
        bucket_name: letstestthis
      run: |
        terraform apply -auto-approve \
          -var="credentials_path=data:text/plain;charset=utf-8;base64,${{ secrets.GCP_KEY }}" \
          -var="project_id=${project_id}" \
          -var="region=${region}" \
          -var="bucket_name=${bucket_name}"
