name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      env:
        project_id: neural-water-404520
        region: us-central1
        bucket_name: letstestthis
      run: |
        /home/runner/work/_temp/50968fed-c8c7-4170-a70e-5f55cd3a0cbd/terraform-bin apply -auto-approve \
          -var="credentials_path=./neural-water-404520-2b5b17d0cb26.json" \
          -var="project_id=${project_id}" \
          -var="region=${region}" \
          -var="bucket_name=${bucket_name}"
