name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allowing manual triggering using GitHub Dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init

    - name: Prompt for Inputs
      id: input
      run: |
        echo "::set-output name=project_id::$(read -p 'Enter GCP Project ID: ' var && echo $var)"
        echo "::set-output name=region::$(read -p 'Enter GCP Region: ' var && echo $var)"
        echo "::set-output name=bucket_name::$(read -p 'Enter Bucket Name: ' var && echo $var)"

    - name: Apply Terraform changes
      env:
        project_id: ${{ steps.input.outputs.project_id }}
        region: ${{ steps.input.outputs.region }}
        bucket_name: ${{ steps.input.outputs.bucket_name }}
      run: |
        terraform apply -auto-approve \
          -var="credentials_path=./neural-water-404520-2b5b17d0cb26.json" \
          -var="project_id=${project_id}" \
          -var="region=${region}" \
          -var="bucket_name=${bucket_name}"
