name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Google Cloud Platform Project ID'
        required: true
        type: string
      region:
        description: 'GCP Region for the resources'
        required: true
        type: string
      bucket_name:
        description: 'Name for the Google Cloud Storage bucket'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      env:
        project_id: ${{ github.event.inputs.project_id }}
        region: ${{ github.event.inputs.region }}
        bucket_name: ${{ github.event.inputs.bucket_name }}
      run: |
        terraform apply -auto-approve \
          -var="gcp_credentials_path=./neural-water-404520-2b5b17d0cb26.json" \
          -var="gcp_project_id=${project_id}" \
          -var="gcp_region=${region}" \
          -var="storage_bucket_name=${bucket_name}"
